// 4 free (left) → 4 premium (right)
export const CHARACTERS = [
  {
    id: 'chloe',
    name: 'Chloe',
    role: 'The Playful One',
    isPremium: false,
    colorHex: '#c9a96e',
    image: require('../assets/images/characters/chloe.webp'),
  },
  {
    id: 'maya',
    name: 'Maya',
    role: 'The Caring Soul',
    isPremium: false,
    colorHex: '#7c3aed',
    image: require('../assets/images/characters/maya.png'),
  },
  {
    id: 'mia',
    name: 'Mia',
    role: 'The Adventurer',
    isPremium: false,
    colorHex: '#e879a0',
    image: require('../assets/images/characters/mia.png'),
    // scale up slightly so no black gap after translateX shift
    imageTransform: [{ scale: 1.18 }, { translateX: -40 }],
  },
  {
    id: 'harper',
    name: 'Harper',
    role: 'The Intellectual',
    isPremium: false,
    colorHex: '#3b82f6',
    image: require('../assets/images/characters/harper.webp'),
  },
  {
    id: 'aisha',
    name: 'Aisha',
    role: 'The Mysterious One',
    isPremium: true,
    colorHex: '#d4af37',
    image: require('../assets/images/characters/aisha.webp'),
  },
  {
    id: 'hana',
    name: 'Hana',
    role: 'The Gentle Heart',
    isPremium: true,
    colorHex: '#f472b6',
    image: require('../assets/images/characters/hana.png'),
  },
  {
    id: 'jasmine',
    name: 'Jasmine',
    role: 'The Passionate One',
    isPremium: true,
    colorHex: '#f97316',
    image: require('../assets/images/characters/jasmine.png'),
  },
  {
    id: 'rin',
    name: 'Rin',
    role: 'The Ethereal Beauty',
    isPremium: true,
    colorHex: '#22d3ee',
    image: require('../assets/images/characters/rin.png'),
  },
];
